apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-oh5i
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cphn-tenant/rhtap-demo-app/hacbs-test-project-oh5i@sha256:1cc4172c33f4c64de643c5eccb878ab45f90124dd5dffa330ff13123e553c4b1
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
