apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-oh5i
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cphn-tenant/rhtap-demo-app/hacbs-test-project-oh5i@sha256:843ad92424d757642bd437189ad5a6bd29af25543ce51abcab3d1fe596c07e67
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
