apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-oh5i
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cphn-tenant/rhtap-demo-app/hacbs-test-project-oh5i@sha256:cc1ab27681346643354b760a352f0dc79c5ccc6411112c004bfb2fa898dc97ce
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
